messenger/urls.py
from django.urls import path
from messenger.view import *

app_name="messenger"

urlpatterns = [
    path('signup/',SignupView.as_view(),name="sign_up"),
    path('login/',LoginView.as_view(),name="loginpage"),
    path('logout/',logout_user,name="logoutpage"),

    path('msg/',message_view.as_view(),name='msg'),
    path('msg/chat/<int:pk>',chat_view.as_view(),name='chat'),
]

whatsupp/urls.py
from django.contrib import admin
from django.urls import path
from messenger.urls import *
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wtsapp/',include('messenger.urls')),
]

messenger/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Message(models.Model):
    fromuser=models.IntegerField(default=0)
    touser=models.IntegerField(default=0)
    chattext = models.TextField("ChatBox",default=" ")

messenger/forms/messageform.py
from django import forms
from messenger.models import *
from django.forms import Textarea

class MessageForm(forms.ModelForm):
    class Meta(object):
        model=Message
        exclude=['fromuser','touser']
        widgets = {
            'chattext': Textarea(attrs={'cols': 50, 'rows': 4}),
        }

messenger/views.py
from django.shortcuts import render

# Create your views here.

messenger/templates/_basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Onlineapp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#">Features</a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#">Pricing</a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#">About</a>-->
      <!--</li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <!--<input class="form-control mr-sm-2" type="text" placeholder="Search">-->
      <!--<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>-->
    </form>
  </div>
</nav>
    {% block content %}
    {% endblock %}
</body>
</html>

messenger/templates/chathtml.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Whatsupp_Chat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
            * {
                box-sizing: border-box;
            }

            #innerbox
            {
               width:50%; /* or whatever width you want. */
               max-width:50%; /* or whatever width you want. */
               display: inline-block;
            }




            body {
              margin: 0;
            }

            /* Style the header */
            .header {
                background-color: #f1f1f1;
                padding: 1px;
                text-align: center;
            }


            .main {
                display: table;
                width:100%;
                border: solid 1px;
            }
            .inner {
                display:table-cell;
                height: 100%;
                vertical-align:middle;
                margin-bottom: 25px;
                margin-top: 40px;
                min-height: 450px;

            }
            .top{
                background:#dcf8c6;
                height: 300px;
                overflow-y: scroll;
            }

            .bottom {
                background:#ece5dd;
                height: 145px;
             }

            /* Style the top navigation bar */
            .topnav {
                overflow: hidden;
                background-color: #25d366;
            }

            /* Style the topnav links */
            .topnav a {
                float: right;
                display: block;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            /* Change color on hover */
            .topnav a:hover {
                background-color: #ddd;
                color: black;
            }

            /* Create three unequal columns that floats next to each other */
            .column {
                float: left;
                padding: 10px;
            }

            /* Left and right column */
            .column.side {
                width: 25%;
            }

            /* Middle column */
            .column.middle {
                width: 50%;
                background-color: #F5F5F5;
                float: left;
                height: 300px;
                margin-bottom: 25px;
                margin-top: 40px;
                min-height: 450px;
            }

            /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }

            /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 600px) {
                .column.side, .column.middle {
                    width: 100%;
                }
            }

            /* Style the footer */
            .footer {
                background-color: #f1f1f1;
                padding: 10px;
                text-align: center;
            }
    </style>
</head>
<body>


       <div class="header">
        </div>

        <div class="topnav">
          <a href="{% url 'messenger:logoutpage' %}">Logout</a>
            <a  style="float:left"><b>Whatsupp</b></a>
        </div>

        <div class="row ">
          <div class="column side">
            <h2>Friends</h2>
              <div >
                    <table border="0">
                            {% for i in object_list %}
                                <tr>
                                    {% ifnotequal userid i.id %}
                                        <td>
                                            <a href='{% url "messenger:chat" i.id %}'>{{i.username}}</a>
                                        </td>
                                    {% endifnotequal %}
                                </tr>
                            {% endfor %}
                    </table>
              </div>
          </div>
          <div class="column middle">
                <div class="main">
                    <div class="inner">
                        <div class="top">
                             <table border="0" width="790">
                                        {% for i in chat %}
                                            <tr>
                                                <div class="innerbox" style="width:50%; overflow: hidden; cursor:pointer">
                                                {% ifequal userid i.fromuser %}
                                                    {% ifequal to i.touser %}
                                                <!--{{myname}}:-->
                                                        <td style="float:left">{{i.chattext}}</td>
                                                    {% endifequal%}
                                                {% endifequal%}
                                                {% ifequal userid i.touser %}
                                                    {% ifequal to i.fromuser %}
                                                <!--{{frdname}}:-->
                                                        <td style="float:left">{{i.chattext}}</td>
                                                    {% endifequal%}
                                                {% endifequal%}

                                                </div>
                                            </tr>
                                        {% endfor %}
                                </table>
                        </div>
                        <div class="bottom">
                            <form method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
                                {% csrf_token %}
                                {{ form.as_p }}
                                <p>
                                    <input type='submit' value="send" />
                                </p>
                            </form>
                        </div>
                    </div>
                </div>

          </div>
          <div class="column side">
          </div>
        </div>

        <div class="footer">
          <b>Chat with Fun</b>
        </div>
</body>
</html>

messenger/templates/college_delete.html
{% extends "_basic.html" %}
{%block content%}
    <form method="post">
        {% csrf_token %}
        <p>Are you want to delete "{{object}}"</p>
        <input type="submit" value="confirm"/>
    </form>
{%endblock%}

messenger/templates/college_form_template.html
{% extends "_basic.html" %}
{% block content %}
<form method = "post">
    {% csrf_token %}
    {{form}}
    <input type = "submit">
</form>
{% endblock %}

messenger/templates/collegefile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>college file</title>
</head>
<body>
<h1>hello world</h1>
<h4>{{shy}}</h4>
    <table border="1" align="center">
        <tr>
            <th>name</th>
            <th>email</th>
            <th>{{s}}</th>
        </tr>


        {% for i in student_details %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.email}}</td>
            </tr>
        {% endfor %}
    </table>

    <button onclick="http://127.0.0.1:8000/stud/3">click me hard</button>
</body>
</html>

messenger/templates/collegefileacronym.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>college file acronym</title>
</head>
<body>
    <table border="1" align="center">
        <tr>
            <th>name</th>
            <th>email</th>
            <th>acronym</th>
        </tr>


        {% for i in student_det %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.college__acronym}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

messenger/templates/collegestudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>College student</title>
</head>
<body>
    {% if 'onlineapp.add_student' in user_permissions %}
    <input type="button" onclick="location.href='http://127.0.0.1:8000/onlineapp/college/{{num}}/add'" value="Add student ">
    {% endif %}
    <table border="1" align="center">
        <tr>
            <th>name</th>
            <th>email</th>
            <th>colloge</th>
            <th>total</th>
            {% if 'onlineapp.change_college' in user_permissions  and 'onlineapp.delete_college' in user_permissions %}
            <th>options</th>
            {% endif %}
        </tr>
        {% for i in stu_det %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.college__acronym}}</td>
                <td>{{i.mocktest1__total}}</td>                                                                <!--collegeid,studentid-->
                {% if 'onlineapp.change_college' in user_permissions  and 'onlineapp.delete_college' in user_permissions %}
                <td><a href="http://127.0.0.1:8000/onlineapp/college/{{num}}/{{i.id}}/edit">edit</a>/<a href="http://127.0.0.1:8000/onlineapp/college/{{num}}/{{i.id}}/delete">delete</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>

</body>
</html>

messenger/templates/index.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Ponynote</title>
  </head>
  <body>
    <div id="root">
    </div>
      {% render_bundle 'main' %}
  </body>
</html>

messenger/templates/messagehtml.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message form</title>
</head>
<body>


<table border="1"  id="students">
        <tr>
            <th>name</th>
            <!--<th>receiver</th>-->
            <!--<th>text</th>-->
        </tr>


        {% for i in form %}
            <tr>
                <td><a href="http://127.0.0.1:8000/wtsapp/msg/chat/{{i.author}}">{{i.author}}</a></td>
                <!--<td>{{i.recipient}}</td>-->
                <!--<td>{{i.text}}</td>-->
            </tr>
        {% endfor %}
    </table>


<h1>hello vanakum</h1>
</body>
</html>

messenger/templates/sarikamsghtml.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Whatsupp_User_lists</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
            * {
                box-sizing: border-box;
            }

            body {
              margin: 0;
            }

            /* Style the header */
            .header {
                background-color: #f1f1f1;
                padding: 1px;
                text-align: center;
            }

            /* Style the top navigation bar */
            .topnav {
                overflow: hidden;
                background-color: #25d366;
            }

            /* Style the topnav links */
            .topnav a {
                float: right;
                display: block;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            /* Change color on hover */
            .topnav a:hover {
                background-color: #ddd;
                color: black;
            }

            /* Create three unequal columns that floats next to each other */
            .column {
                float: left;
                padding: 10px;
            }

            /* Left and right column */
            .column.side {
                width: 25%;
            }

            /* Middle column */
            .column.middle {
                width: 50%;
                background-color: #F5F5F5;
                float: left;
                height: 300px;
                margin-bottom: 25px;
                margin-top: 40px;
                overflow-y: scroll;
                min-height: 450px;
            }

            /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }

            /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 600px) {
                .column.side, .column.middle {
                    width: 100%;
                }
            }

            /* Style the footer */
            .footer {
                background-color: #f1f1f1;
                padding: 10px;
                text-align: center;
            }
    </style>
</head>
<body>


       <div class="header">
        </div>

        <div class="topnav">
          <a href="{% url 'messenger:logoutpage' %}">Logout</a>
            <a  style="float:left"><b>Whatsupp</b></a>
        </div>

        <div class="row ">
          <div class="column side">
            <h2>Friends</h2>
              <div >
                    <table border="0">
                            {% for i in object_list %}
                                <tr>
                                    {% ifnotequal userid i.id %}
                                        <td>
                                            <a href='{% url "messenger:chat" i.id %}'>{{i.username}}</a>
                                        </td>
                                    {% endifnotequal %}
                                </tr>
                            {% endfor %}
                    </table>
              </div>
          </div>
          <div class="column middle">

                <hr/>
          </div>

          <div class="column side">
          </div>
        </div>

        <div class="footer">
          <b>Chat with Fun</b>
        </div>
</body>
</html>

messenger/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Khula' rel='stylesheet'>
    <style>
            * {
                box-sizing: border-box;
            }

            body {
              margin: 0;
            }

            /* Style the header */
            .header {
                background-color: #f1f1f1;
                padding: 1px;
                text-align: center;
            }

            /* Style the top navigation bar */
            .topnav {
                overflow: hidden;
                background-color: #25d366;
                <!--#333-->
            }

            /* Style the topnav links */
            .topnav a {
                float: right;
                display: block;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            /* Change color on hover */
            .topnav a:hover {
                background-color: #ddd;
                color: black;
            }

            /* Create three unequal columns that floats next to each other */
            .column {
                float: left;
                padding: 10px;
            }

            /* Left and right column */
            .column.side {
                width: 25%;
            }

            /* Middle column */
            .column.middle {
                width: 50%;
            }

            /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }

            /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
            @media screen and (max-width: 600px) {
                .column.side, .column.middle {
                    width: 100%;
                }
            }

            /* Style the footer */
            .footer {
                background-color: #f1f1f1;
                padding: 10px;
                text-align: center;
            }
    </style>
</head>

<body>
        <div class="topnav">
          <a href="../signup/">Register</a>
          <a href="../login/">Login</a>
          <a>Home</a>
          <a  href="" style="float:left"><b>Whatsupp</b></a>
        </div>

        <div class="row ">
          <div class="column side">
          </div>
              <div class="column middle">
                    <div class="panel panel-default" style="color:#808000">
                        <div class="panel-heading">
                            <h2><b>Signup <Form></Form></b></h2>
                        </div>

              </div>
          <div class="column side">
          </div>
        </div>

        <div class="panel-footer"></div>
        </div>
</body>

{% block content %}
<center>
<form method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit">
</form>
</center>
{% endblock %}

messenger/templates/student_form_template.html
{% extends "_basic.html" %}
{% block content %}
<form method = "post">
    {% csrf_token %}
    {{student_form}}
    {{test_form}}
    <input type = "submit">
</form>
{% endblock %}

messenger/templates/studentfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>student details</title>
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
</head>
<body>
    <button onclick="location.href='http://127.0.0.1:8000/studmarks'" type="button">
     get marks</button>
    <table border="1" align="center">
        <tr>
            <th>name</th>
            <th>email</th>
            <th>acronym</th>
        </tr>
        {% for i in student_details %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.college__acronym}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

messenger/templates/studentmarks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>student marks</title>
</head>
<body>
    <table border="1" align="center">
        <tr>
            <th>name</th>
            <th>email</th>
            <th>marks</th>
        </tr>
        {% for i in student_details %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.mocktest1__total}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>